version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: goatfarm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  backend:
    build:
      context: ./goat-farm-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/goatfarm
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      APP_JWT_SECRET: ${APP_JWT_SECRET:-ODU0YzJjYjgtYjZhZi00Zjk1LWI0ZTYtNzA1ZDY3ZjViMGRlOTQ1NDI0M2M0NjEz}
    depends_on:
      - postgres
      - redis
    ports:
      - '8080:8080'

  frontend:
    build:
      context: ./goat-farm-frontend
    depends_on:
      - backend
    ports:
      - '5173:4173'

volumes:
  pgdata:
